version: "3.7"
services:
  #Jupyter notebook
  jupyter-notebook:
    build:
      context: ./
      dockerfile: ./docker-jupyter/Dockerfile
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./:/home/jovyan/work/notebooks/

networks:
  default_net: